#!/usr/bin/env node

"use strict"

var path = require('path')
var spawn = require('child_process').spawn
var assert = require('assertf')
var bl = require('bl')

process.on('uncaughtException', require('workshop-assertion-message'));

var submission = process.argv[2]

assert.ok(submission, 'verify expects a package name\n e.g. `npm-tutor verify commander`')

submission = submission.trim()

spawn('npm', 'ls --json --depth=1 --global'.split(' '))
.stdout.pipe(bl(function(err, data) {
  assert.ifError(err)
  var ls = JSON.parse(data)
  var names = Object.keys(ls.dependencies)

  var min = names.reduce(function(min, key) {
    var numDeps = ls.dependencies[key].dependencies ? Object.keys(ls.dependencies[key].dependencies).length : 0;
    if (numDeps < min) return numDeps
    return min
  }, Infinity)

  var minDepsNames = names.filter(function(key) {
    var numDeps = ls.dependencies[key].dependencies ? Object.keys(ls.dependencies[key].dependencies).length : 0;
    return (numDeps == min)
  })

  assert.ok(names.indexOf(submission) !== -1, "Uh, it doesn't seem that %s is installed globally?", submission)
  assert.ok(minDepsNames.indexOf(submission) !== -1, 'Nope, there exists a package with fewer than %s dependencies.', Object.keys(ls.dependencies[submission]).length)

  console.info('\nGreat parsing skills! %s has got %d dependencies. Correct.\n', submission, min)
}))
