#!/usr/bin/env node

"use strict"

var path = require('path')
var assert = require('assertf')

process.on('uncaughtException', require('workshop-assertion-message'));

var answer = 'glob'

var submission = process.argv[2]
assert(submission, 'Which package??')
submission = submission.trim()

assert.equal(submission, answer, 'Nope.')
console.info('Correct!')
