#!/usr/bin/env node

"use strict"

var assert = require('assert')
process.on('uncaughtException', require('workshop-assertion-message'));

var exec = require('child_process').exec
var getLatest = require('./latest-npm')

console.info('Getting latest stable version of npm...')

getLatest(function(err, latest) {
  assert.ifError(err)
  exec('npm -v', function(err, stdout) {
    assert.ifError(err)
    var current = stdout.trim()
    assert.equal(current, latest, "Oh dear, " + current + " is not the latest stable version of npm.\nThe latest version is "+latest+".\n\nGo to https://www.npmjs.org/doc/misc/npm-faq.html#how-do-i-update-npm- for instructions on how to update to the latest stable version of npm.")
    console.info('\nThat is good. You are using the latest stable version of npm: %s', latest)
  })
})

