#!/usr/bin/env node

"use strict"

var fs = require('fs')
var path = require('path')
var assert = require('assert')

process.on('uncaughtException', require('workshop-assertion-message'));

var targetPackage = path.resolve(process.cwd(), 'package.json')

assert.ok(fs.existsSync(targetPackage), 'Where is your package.json?')

var pkg = require(targetPackage)

assert.deepEqual(Object.keys(pkg).sort(), ['name', 'version'], 'Is that REALLY the minimum package.json??')
assert.equal(pkg.name, "mypackage", 'package name should be mypackage')
assert.ok(pkg.version, 'package version should have a version!')

console.log('\nGreat work! That is really minimal.')
