#!/usr/bin/env node

"use strict"

var fs = require('fs')
var path = require('path')
var assert = require('assertf')
var exec = require('child_process').exec

process.on('uncaughtException', require('workshop-assertion-message'));

exec('npm ls', {cwd: process.cwd()}, function(err) {
  assert.ok(!err, 'Looks like there are extraneous packages!')
  console.info('\nGreat! I found no extraneous packages.')
})
