#!/usr/bin/env node

"use strict"

var path = require('path')
var exec = require('child_process').exec
var assert = require('assertf')
process.on('uncaughtException', require('workshop-assertion-message'));

var submission = process.argv[2]
var dir = path.join(process.env['WORKSHOP_WORKING_DIR'], 'npmls')
assert.ok(submission, 'verify expects a version number\n e.g. `npm-tutor verify 1.2.3`')

submission = submission.trim()

exec('npm ls --json', {cwd: dir}, function(err, data) {
  assert.ifError(err)
  var ls = JSON.parse(data)
  var answer = ls.dependencies.through2.dependencies['readable-stream'].dependencies['string_decoder'].from.split('@')[1]
  assert.equal(submission, answer, '%s is not the correct semver range.\nWe are expecting just the range.\ne.g. verify "~2.2.1"', submission)
  console.info('\nGreat JSON parsing skills. %s is correct.\n', submission)
})
