#!/usr/bin/env node

var spawn = require('child_process').spawn
var workshop = require('../workshop')
var messages = require('../messages')
var help = require('./helpme')

function reset() {
  var args = [].slice.call(arguments)
  workshop.forwardExec('chapter-reset', args, function() {
    workshop.unsetComplete(workshop.getCurrent().name)
    workshop.clear(function() {
      console.log(messages['chapter-reset'], workshop.getCurrent().name)
      help()
    })
  })
}

if (!module.parent) {
  reset.apply(this, process.argv.slice(2))
}

module.exports = reset
