#!/usr/bin/env node

var workshop = require('../workshop')
var messages = require('../messages')

function help() {
  var args = [].slice.call(arguments)
  workshop.forwardExec('help', args, function() {
    if (help.done) help.done()
  })
}

if (!module.parent) {
  help.done = function() {
    console.log(messages['help'])
    console.log(messages['remaining'], workshop.toDo().length, workshop.exercises.length)
  }
  help.apply(this, process.argv.slice(2))
}

module.exports = help
