#!/usr/bin/env node

var spawn = require('child_process').spawn
var workshop = require('../workshop')
var messages = require('../messages')
var help = require('./help')

function next() {
  workshop.next()
}

if (!module.parent) {
  next.apply(this, process.argv.slice(2))
}

module.exports = next
