#!/usr/bin/env node

var spawn = require('child_process').spawn
var workshop = require('../workshop')

function status() {
  console.log(workshop.data.get())
}

if (!module.parent) {
  status.apply(this, process.argv.slice(2))
}

module.exports = status
