#!/usr/bin/env node
var spawn = require('child_process').spawn
var workshop = require('../workshop')
var messages = require('../messages')

function verify() {
  var args = [].slice.call(arguments)
  workshop.verify(args, function(err, valid) {
    if (err) throw err
    if (!valid) {
      process.exit(1)
      return
    }
    console.log()
    console.log(messages['success'])
    if (workshop.allComplete()) return console.log(messages['complete'])
  })
}

if (!module.parent) {
  verify.apply(this, process.argv.slice(2))
}

module.exports = verify
