#!/usr/bin/env node

var spawn = require('child_process').spawn
var workshop = require('../workshop')
var messages = require('../messages')
var help = require('./help')

function reset() {
  workshop.reset(function(err) {
    if (err) throw err
    console.log(messages['restarted'])
    help()
  })
}

if (!module.parent) {
  reset.apply(this, process.argv.slice(2))
}

module.exports = reset
