#!/usr/bin/env node

var spawn = require('child_process').spawn
var workshop = require('../workshop')
var messages = require('../messages')

workshop.reset(function(err) {
  if (err) throw err
  console.log(messages['restarted'])
  spawn('help', [], {
    env: process.env,
    stdio: 'inherit'
  })
})
