#!/usr/bin/env node

"use strict"

var assert = require('assert')
process.on('uncaughtException', require('workshop-assertion-message'));

var semver = require('semver')

var submission = process.argv[2].toLowerCase()

var answer = '2.0.0'
assert.ok(semver.satisfies(answer, '2'))
assert.ok(!semver.satisfies('1.9.9', '2'))
assert.ok(semver.satisfies('2.0.1', '2'))
assert.ok(semver.satisfies('2.0.0', '2'))

assert.equal(submission, '2.0.0', submission + "is incorrect.")

assert.ok(semver.satisfies(answer, '2'))

console.info('\nCorrect! The lowest valid version in the "2" range is 2.0.0\n')
