#!/usr/bin/env node

"use strict"

var fs = require('fs')
var path = require('path')
var assert = require('assert')

process.on('uncaughtException', require('workshop-assertion-message'));

console.info('Checking once is installed...')
var target = path.resolve(process.env['WORKSHOP_WORKING_DIR'], 'node_modules/once')
assert.ok(fs.existsSync(target), 'Hm, the once package must be installed.')
console.info('\nGood one, \'once\' has been installed into ./node_modules.')
