#!/usr/bin/env node

"use strict"

var assert = require('assert')
process.on('uncaughtException', require('workshop-assertion-message'));

var semver = require('semver')

var submission = process.argv[2].toLowerCase()

var answer = '1.3.0'
assert.ok(!semver.satisfies('1.3.0', '~1.2.7'))
assert.ok(semver.satisfies('1.2.99', '~1.2.7'))

assert.equal(submission, '1.3.0', submission + "is incorrect.")
console.info('Correct! The lowest *invalid* version in the ~1.2.7 range is 1.3.0')

