#!/usr/bin/env node

"use strict"

var assert = require('assert')
process.on('uncaughtException', require('workshop-assertion-message'));

var semver = require('semver')

var submission = process.argv[2].toLowerCase()

var answer = '0.3.0'
assert.ok(semver.satisfies(answer, '^0.3.0'))
assert.ok(!semver.satisfies('0.2.0', '^0.3.0'))

assert.equal(submission, answer, submission + " is incorrect.")

console.info('Correct! The lowest valid version in the ^0.3.0 range is 0.3.0')
