#!/usr/bin/env node

"use strict"

var assert = require('assert')
process.on('uncaughtException', require('workshop-assertion-message'));

var semver = require('semver')

var submission = process.argv[2].toLowerCase()

var answer = '3.0.2'
assert.ok(semver.satisfies(answer, '^3.0.2'))

assert.equal(submission, answer, submission + "is incorrect.")

console.info('\nCorrect! The lowest valid version in the ^3.0.2 range is 3.0.2\n')
