#!/usr/bin/env node

"use strict"

var path = require('path')
var exec = require('child_process').exec
var assert = require('assertf')
process.on('uncaughtException', require('workshop-assertion-message'));

var submission = process.argv[2]
var dir = path.resolve(process.env['WORKSHOP_WORKING_DIR'], 'npmls')
assert.ok(submission, 'verify expects a version number\n e.g. `npm-tutor verify 1.2.3`')

submission = submission.trim()

exec('npm ls --json', {cwd: dir}, function(err, data) {
  assert.ifError(err)
  var ls = JSON.parse(data)
  var answer = ls.dependencies.through2.dependencies['readable-stream'].dependencies['string_decoder'].version
  assert.equal(submission, answer, 'Hm. No, %s is not the installed version of string_decoder.', submission)
  console.info('\n%s is correct!\n', answer)
})
