#!/usr/bin/env node

"use strict"

var fs = require('fs')
var path = require('path')
var assert = require('assertf')
var exec = require('child_process').exec

process.on('uncaughtException', require('workshop-assertion-message'));

exec('npm ls --no-color --json', {cwd: process.env['WORKSHOP_WORKING_DIR']}, function(err, stdout, stderr) {
  assert.ok(err, 'I could not find any extraneous packages?') // ignore err
  var ls = JSON.parse(stdout.trim())
  var extraneous = ls.problems.map(function(line) {
    var d = line.split('extraneous: ')
    if (d.length < 2) return false
    var pkgname = d[1].split(' ')
    return pkgname[0]
  }).filter(Boolean)
  assert.ok(extraneous.length, 'I could not find any extraneous packages?')
  console.info('\nGreat! I found extraneous packages: %s.\n', extraneous.join(', '))
})
