#!/usr/bin/env node

"use strict"

var assert = require('assert')
process.on('uncaughtException', require('workshop-assertion-message'));

var semver = require('semver')

var submission = process.argv[2].toLowerCase()

var answer = '1.8.0'
assert.ok(!semver.satisfies(answer, '1.7.x'))
assert.ok(semver.satisfies('1.7.999', '1.7.x'))

assert.equal(submission, answer, submission + " is incorrect.")

console.info('\nCorrect! The lowest invalid version in the 1.7.x range is 1.8.0')

console.info("\n1.7.x will match all versions in the range: ", semver.toComparators('1.7.x')[0].join(' '))
