#!/bin/bash

set -e
chapter-reset

`workshop-exercise dir`/verify
workshop-exercises setComplete `workshop-exercise name` --silent
workshop-exercises setNext --silent

`workshop-exercise dir`/verify
workshop-exercises setComplete `workshop-exercise name` --silent
workshop-exercises setNext --silent

chapter-reset
