#!/usr/bin/env node

"use strict"

var fs = require('fs')
var util = require('util')
var path = require('path')
var assert = require('assert')

process.on('uncaughtException', require('workshop-assertion-message'));

function inspect(obj) {
  return util.inspect(obj, {colors: true, depth: 30})
}

var target = path.resolve(process.cwd(), 'node_modules/once')
var targetPackage = path.resolve(process.cwd(), 'package.json')

assert.ok(fs.existsSync(targetPackage), 'Where is your package.json?')

var pkg = require(targetPackage)

assert.ok(pkg.devDependencies, 'package.json needs devDependencies: ' + inspect(pkg))
assert.ok(pkg.devDependencies['tape'], 'package.json does not have tape as a development dependency: \n' + inspect(pkg))
assert.ok(fs.existsSync(target), 'The tape package must actually be installed!')
assert.ok(pkg.dependencies['tape'], 'package.json must not have tape as a regular dependency: \n' + inspect(pkg))

require('../install-save/verify')
