#!/usr/bin/env node

"use strict"

var fs = require('fs')
var util = require('util')
var path = require('path')
var assert = require('assertf')

process.on('uncaughtException', require('workshop-assertion-message'));

function inspect(obj) {
  return util.inspect(obj, {colors: true, depth: 30})
}

var target = path.resolve(process.cwd(), 'node_modules/once')
var targetPackage = path.resolve(process.cwd(), 'package.json')

assert.ok(fs.existsSync(targetPackage), 'Where is your package.json?')

var pkg = require(targetPackage)

assert.ok(pkg.dependencies, 'package.json needs dependencies:\n' + inspect(pkg))

assert.ok(pkg.dependencies['once'], 'package.json does not have the once dependency:\n' + inspect(pkg))

var target = path.resolve(process.cwd(), 'node_modules/once')
assert.ok(fs.existsSync(target), 'The once package must be installed!')
console.info('\nGreat stuff. You set up \'once\' as a dependency.')
